networktocode/circuit-maintenance-parser

- .travis.yml
- poetry.lock
- pyproject.toml
[GHSA-5jqp-qgf6-3pvh](https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh) affects Pydantic versions <1.8.2.
> Update minimum Pydantic version due to security advisory GHSA-5jqp-qgf6-3pvh

- CHANGELOG.md
- README.md
- circuit_maintenance_parser/cli.py
- circuit_maintenance_parser/parser.py
- circuit_maintenance_parser/parsers/zayo.py
- tests/integration/data/zayo/zayo2.html
- tests/integration/data/zayo/zayo2_result.json
- tests/integration/test_eunetworks.py
- tests/integration/test_ical.py
- tests/integration/test_ntt.py
- tests/integration/test_packetfabric.py
- tests/integration/test_zayo.py
- tests/unit/test_parser.py
- Add another lightly anonymized example Zayo notification email to integration tests
- Some minor code cleanup and a few TODOs to possibly revisit in a future PR
- Improve Zayo parser resilience:
- Use [quopri](https://docs.python.org/3/library/quopri.html) to handle the `quoted-printable` encoding added to the original HTML content
- Handle a few alternate cases that were initially causing exceptions to be thrown when I first attempted parsing this new file.
> Improve reliability of Zayo parser and add another test file for it

- CHANGELOG.md
- circuit_maintenance_parser/__init__.py
- circuit_maintenance_parser/output.py
- circuit_maintenance_parser/parser.py
- circuit_maintenance_parser/providers.py
- tests/unit/test_providers.py
The parsed response from a Provider was not taking the proper `provider` field when it was not present in the notifications, and the default name of the class was required. 
This PR adds the proper test to catch it and the fix.
> Fix default provider when not present in notifications

- circuit_maintenance_parser/parsers/lumen.py
- tests/unit/data/lumen/lumen3.html
- tests/unit/data/lumen/lumen3_result.json
- tests/unit/test_parsers.py
After looking at some email notifications I've spotted some varriations in the strings used to match data. There is also a possibility that a notification can have an empty table.
`"scheduled maintenance #:"` can sometimes be used to identify the ID, and `"This maintenance is scheduled"` can be used to find the status.
Testing has been added to ensure these variations.
> Lumen Variations

- README.md
- circuit_maintenance_parser/__init__.py
- circuit_maintenance_parser/parsers/turkcell.py
- circuit_maintenance_parser/providers.py
- tests/unit/data/turkcell/turkcell1.html
- tests/unit/data/turkcell/turkcell1_result.json
- tests/unit/data/turkcell/turkcell2.html
- tests/unit/data/turkcell/turkcell2_result.json
- tests/unit/test_providers.py
> Turkcell Parser

- circuit_maintenance_parser/data.py
- tests/unit/test_data.py
- tests/unit/test_init.py
While working on a new CSV parser, we found that we were not taking properly the payload data, so now we add the `decode=True` option
See: https://docs.python.org/3.5/library/email.message.html#email.message.Message.get_payload
> Extend email parsing support for encoded attachements

- README.md
- tests/unit/test_providers.py
Provider tests should only test Provider methods logic, not particular Provider implementations, that are already tested in the End to End tests.
> Make Provider tests independent of particular Providers

- CHANGELOG.md
- circuit_maintenance_parser/__init__.py
- circuit_maintenance_parser/cli.py
- circuit_maintenance_parser/data.py
- tests/unit/test_data.py
- tests/unit/test_e2e.py
- tests/unit/test_init.py
- tests/unit/test_processors.py
- tests/unit/test_providers.py
Addresses issue #58 
Ensure `try/except` pattern for any issue found while initializing `NotificationData` from the library client, returning empty data.
I know it's too open, but because there could be multiple errors I tried to make it the simplest in the code instead of documenting all the potential exceptions each method could raise.
> Issue-58: Ensure safety usage of the init_data methods

- circuit_maintenance_parser/parsers/lumen.py
Handle the potential Lumen status values of "Not Completed" and "Postponed", as seen in actual emails.
Additionally, for some updates to an existing maintenance, there is no column in the table describing the status. To avoid an error in this case (status is a mandatory field), I'm setting the status to a default of "CONFIRMED" - is this the best way to handle this?
> Handle more potential Lumen statuses seen in the field

- CHANGELOG.md
- circuit_maintenance_parser/parser.py
- circuit_maintenance_parser/parsers/equinix.py
- circuit_maintenance_parser/provider.py
- tests/unit/data/equinix/equinix1_result_combined.json
- tests/unit/data/equinix/equinix3.eml
- tests/unit/data/equinix/equinix3_result.json
- tests/unit/data/equinix/equinix3_result_combined.json
- tests/unit/test_e2e.py
- tests/unit/test_parsers.py
- Avoid an undefined `impact` variable if the impact type is unrecognized (will likely still fail, but at least now we return a `None` rather than raising an exception)
- Add recognition of reduced-redundancy as an impact type
- Make the maintenance-id matching in the email subject line more conservative
- Add an `_include_filter` to ignore other types of Equinix emails
- Rename `equinix3_result.json` to `equinix1_result_combined.json` to more closely match its meaning and usage
> Equinix improvements

- CHANGELOG.md
- circuit_maintenance_parser/utils.py
Fixes #121.
Instead of calling `tzwhere.tzwhere()` as a consequence of simply doing an `import circuit_maintenance_parser`, only call it when it's actually needed, by implementing it as a `classproperty` of the `Geolocator` class. Verified that this substantially reduces the baseline memory cost of `import circuit_maintenance_parser`.
I also explored replacing `tzwhere` with `timezonefinder`, which appears to be a more up-to-date, more memory-efficient fork, but found that while the peak memory cost of using `timezonefinder.TimezoneFinder()` instead of `tzwhere.tzwhere()` is much lower, `import timezonefinder` appears to cost about 20 MB more RAM than `import tzwhere`. So for the time being I didn't make that change, but we can revisit it if desired.
> Defer loading of tzwhere until it's needed

- circuit_maintenance_parser/data.py
- tests/unit/data/gtt/gtt7.eml
- tests/unit/data/gtt/gtt7_html_parser_result.json
- tests/unit/data/gtt/gtt7_result.json
- tests/unit/test_e2e.py
- tests/unit/test_parsers.py
Handle RFC2047 encoding of non-ASCII characters in subject lines. For example, decode `Subject:` `=?UTF-8?Q?=5Bmaint=2Dnotices=5D_EXA_Emergency_Work_Notification_TT_6543?=^M
=?UTF-8?Q?0619_=E2=80=93_New?=^M` to `[maint-notices] EXA Emergency Work Notification TT 65430619 – New`.
> Handle encoding of non-ASCII characters in email subjects

- circuit_maintenance_parser/provider.py
Exclude customer support emails from Telia that don't include a maintenance notification.
> Add exclude filter for Telia

- CHANGELOG.md
- README.md
- circuit_maintenance_parser/output.py
- circuit_maintenance_parser/parsers/equinix.py
- circuit_maintenance_parser/parsers/lumen.py
- tests/unit/data/equinix/equinix4.eml
- tests/unit/data/equinix/equinix4_result.json
- tests/unit/data/equinix/equinix4_result_combined.json
- tests/unit/data/lumen/lumen7.html
- tests/unit/data/lumen/lumen7_result.json
- tests/unit/test_e2e.py
- tests/unit/test_output.py
- tests/unit/test_parsers.py
- Some Equinix emails don't clearly state "SCHEDULED" or "COMPLETED" (etc.) in their subject - default status of these emails to `CONFIRMED` for lack of any better contextual information.
- Lumen parser wasn't handling status `Cancelled` - add support for it.
- I think I went a bit too far in #125 by defaulting `status = Status.NO_CHANGE` globally, it's better to keep it as something that will raise an error if the parser doesn't set an appropriate value for it.
> More fixes

- CHANGELOG.md
- circuit_maintenance_parser/cli.py
- circuit_maintenance_parser/parsers/equinix.py
- circuit_maintenance_parser/utils.py
- poetry.lock
- pyproject.toml
- tests/unit/test_e2e.py
- tests/unit/test_parsers.py
- tests/unit/test_providers.py
Fixes #142 .
The parser was failing due to the exclusion of the year of the maintenance in the timestamp. The detailed time from the notification does not include the year, which is listed on a different line.
This fix parses the start and end year and adds it to the start and end date/time to get an accurate timestamp.
> Fix Equinix Parser

- circuit_maintenance_parser/parsers/colt.py
- tests/unit/data/colt/colt3_result.json
- tests/unit/data/colt/colt5_result.json
- tests/unit/data/colt/colt5_subject_parser_2_result.json
Colt specifies dates with the day first.  I.E. 07/8/2021 is August 7th, not July 8th.
> Colt parser: use European-style day-first date parsing

- circuit_maintenance_parser/parsers/zayo.py
- tests/unit/data/zayo/zayo9.eml
- tests/unit/data/zayo/zayo9_html_parser_result.json
- tests/unit/data/zayo/zayo9_result.json
- tests/unit/test_e2e.py
- tests/unit/test_parsers.py
This handles a case where the Zayo table uses "Customer Circuit ID" in the header rather than "Legacy Circuit ID", which caused the parser to crash.
> Handle Zayo table with "Customer Circuit ID" header

- circuit_maintenance_parser/provider.py
- poetry.lock
- pyproject.toml
- tests/unit/data/zayo/zayo10.eml
- tests/unit/data/zayo/zayo10_html_parser_result.json
- tests/unit/data/zayo/zayo10_result.json
Related to [Zayo email fails parser on email signature](https://github.com/networktocode/circuit-maintenance-parser/issues/175)
changes made to circuit_maintenance_parser/provider.py
Adds chardet.detect method before decoding data_part.content
> added chardet encoding detection in filer_check

- circuit_maintenance_parser/parsers/zayo.py
- tests/unit/data/zayo/zayo5_html_parser_result.json
- tests/unit/data/zayo/zayo5_result.json
- tests/unit/data/zayo/zayo6_html_parser_result.json
- tests/unit/data/zayo/zayo6_result.json
- tests/unit/data/zayo/zayo7_html_parser_result.json
- tests/unit/data/zayo/zayo7_result.json
- tests/unit/data/zayo/zayo8_html_parser_result.json
- tests/unit/data/zayo/zayo8_result.json
- tests/unit/data/zayo/zayo9_html_parser_result.json
- tests/unit/data/zayo/zayo9_result.json
- tests/unit/test_parsers.py
As we described in #210, instead of consolidating all activity dates into one large window, we split each maintenance window into a separated maintenance notification object. 
For example: 
an email (attached to #210) from Zayo containing these dates:
```
Maintenance Window 
1st Activity Date 
14-Feb-2023 22:00 to 15-Feb-2023 05:00 ( Central ) 
15-Feb-2023 04:00 to 15-Feb-2023 11:00 ( GMT ) 
2nd Activity Date 
15-Feb-2023 22:00 to 16-Feb-2023 05:00 ( Central ) 
16-Feb-2023 04:00 to 16-Feb-2023 11:00 ( GMT ) 
3rd Activity Date 
16-Feb-2023 22:00 to 17-Feb-2023 05:00 ( Central ) 
17-Feb-2023 04:00 to 17-Feb-2023 11:00 ( GMT ) 
``` 
would yield three notification objects:
```
#circuit-maintenance-parser --data-file ~/zayo_test_email.eml --data-type html --provider-type zayo
Circuit …
```
> Issue #210: Ability to parse multiple maintenance windows from Zayo maintenance notification

- circuit_maintenance_parser/__init__.py
Longer term it would be nice to replace this omission-prone hard-coded list and instead do something like automatically pulling in all non-abstract subclasses of `GenericProvider`.
> Add missing Arelion entry to SUPPORTED_PROVIDERS

- circuit_maintenance_parser/parsers/equinix.py
- tests/unit/data/equinix/equinix6.eml
- tests/unit/data/equinix/equinix6_result.json
- tests/unit/data/equinix/equinix6_result_combined.json
- tests/unit/data/equinix/equinix7.eml
- tests/unit/data/equinix/equinix7_result.json
- tests/unit/data/equinix/equinix7_result_combined.json
- tests/unit/data/equinix/equinix8.eml
- tests/unit/data/equinix/equinix8.json
- tests/unit/data/equinix/equinix8_result.json
- tests/unit/data/equinix/equinix8_result_combined.json
- tests/unit/data/equinix/equinix9.eml
- tests/unit/data/equinix/equinix9_result.json
- tests/unit/data/equinix/equinix9_result_combined.json
- tests/unit/test_e2e.py
- tests/unit/test_parsers.py
This makes five changes:
1. It now handles cancel messages.
2. Equinix sometimes uses `<strong>` instead of `<bold>`, so I updated the beautifulsoup calls to look for both (and changed` _parse_b()` to `_parse_bolded()` to be more accurate).
3. UTC: was never found in my sample messages in `b_elem`, but it was always in `b_elem.text`, so I updated that. Tests still pass and it parses the messages I am receiving from Equinix.
4. "There will be service interruptions" was found in `impact_line` in my messages, not i`mpact_line.next_sibling` (which was None and thus causing an exception).  I reworked it to do both checks, and also not crash if `impact_line` does not have a `next_sibling`.
5. I added tests for the new code, using messages I've received from Equinix as the source, with …
> Improve Equinix parsing

- circuit_maintenance_parser/output.py
This fixes the issue reported by https://github.com/networktocode/circuit-maintenance-parser/pull/259#issuecomment-1965547758
While the test code validated that this was working, the bad logic worked because `str(values["status"])` would be prefaced by `Status.`.  So I corrected both the list and the logical operator.
> Correct incorrect logic in validation code

- circuit_maintenance_parser/output.py
- circuit_maintenance_parser/parser.py
- circuit_maintenance_parser/provider.py
Although v2.6.0 claims to be backwards-compatible with Pydantic 1.x, using it with `nautobot-circuit-maintenance` with Pydantic 1.x causes it to throw exceptions in several places. This PR fixes those.
> Fix various exceptions under Pydantic 1.x

- circuit_maintenance_parser/parser.py
Was testing out the LLM parser and realised that there were a lot of inconsistencies passing in the same email multiple times.
The LLM API has a lot of issues converting the date string into epoch time.
I've messed around with the API directly by asking it questions like "Please convert the following time <> into an epoch string" (I wanted to avoid using a full email as I thought there might have been some special characters in the middle of the strings).
It still couldn't do it consistently. I also did checks prior to the epoch being converted and can see that the LLM can extract the datetime str correctly every time... It just couldn't do the conversion.
I asked the same question directly to the ChatGPT application on my local PC and this worked flawlessly, so there must be some …
> Move epoch parser outside of LLM due to inconsistencies

- circuit_maintenance_parser/parser.py
Noticed that the LLM cannot parse multiple windows as it has no where in the json to store that data. We need the LLM to extract the extra maintenance window values from the email, and store them somewhere in the return data so that the rest of the code knows that there should be multiple maintenances(windows) in the single email. I have done this below with the 'backup_windows' key which is a list. This list will contain all start/end pairs that the LLM can find, that are not the main window.
Had some discussions with @chadell via DM and discussed the possibility of doing this with the code changes below. Christian also mentioned the possibility of improving this to convert the entire parsing into a loop.
Creating this pull request so we can collaborate on these changes.
> Add multi-windows for LLM

- circuit_maintenance_parser/parser.py
I’ve been testing some more with the LLM and noticed some things which I can recommend to you if you wanted to make changes to the LLM question initially asked.
Impact value returned:
I’ve noticed that when the LLM is parsing an email, it can accurately determine the impact of a maintenance which is great. However, the generated_json from the llm will literally return a string of the impact from the email. In my case, I tested with a Tampnet email, and in their impact statement they literally write “NO-IMPACT”. This is what is returned in the generated_json from the LLM, but when you look at the data returned at the end of the process of structuring the metadata, my impact was equal to “OUTAGE”.
The reason the code does this is because of the section here:
```
def _get_impact(self, …
```
> return proper impact result for LLM parsing
